version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BASE_URI=https://run.mocky.io/v3
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"